### ISSUE TITLE
Python IPFS HTTP Client throwing an exception : Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by ManojTaleka** [ipfs-shipyard/py-ipfs-http-client#298] opened 2021-09-17 05:32 UTC
I have installed IPFS CLI version 0.8.0 and tried to connect using python ipfshttpclient. But unfortunately it is throwing an exception "Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)". Anyone has an idea how we can fix this issue?

**Comment by unbeatable-101** [comment] 2021-09-18 11:12
Try changing `VERSION_MAXIMUM   = "0.9.0" ` to 0.10.0

**Comment by jacekv** [comment] 2021-09-22 07:53
Which version of ipfshttpclient are you using? The newest version 0.7.0 supports IPFS clients up to version 0.9.0. 
I think you have to update your ipfshttpclient version.

**Comment by gibcheesepuffs** [comment] 2021-10-04 07:04
Getting same error, I am using 0.7.0.

**Comment by kasteph** [comment] 2023-05-16 18:05
This actually looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

Thanks.

**Closed by kasteph** 2023-05-16 18:05 UTC
