### ISSUE TITLE
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.11.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by asafd11** [ipfs-shipyard/py-ipfs-http-client#310] opened 2022-01-28 14:10 UTC
any idea how to fix this?

**Comment by pintman** [comment] 2022-02-02 15:13
same here

**Comment by veqtor** [comment] 2022-02-19 07:57
this project is abandoned more or less

**Comment by kasteph** [comment] 2023-05-16 18:05
This actually looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

Thanks.

**Closed by kasteph** 2023-05-16 18:05 UTC
