### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by Narendhraprasth** [ipfs-shipyard/py-ipfs-http-client#250] opened 2021-03-03 07:27 UTC
Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)

always some errors like this does happen can anyone help me ? i kind of tried the irc freenode but it doesn't work at all

**Comment by marcusbeckerman** [comment] 2021-03-25 00:59
I went into the package folder and opened `client/__init__.py` and changed the `VERSION_MAXIMUM` to  `"0.8.1"` on line 19, I haven't encountered any errors yet. Hopefully devs can push an update to officially support 0.8.0 soon.

**Comment by c0llab0rat0r** [comment] 2021-05-18 21:52
Version `0.8.0a1` has been published to PyPi.

**Comment by kasteph** [comment] 2023-05-16 18:03
This looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

**Closed by kasteph** 2023-05-16 18:03 UTC
