### ISSUE TITLE
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by avatar-lavventura** [ipfs-shipyard/py-ipfs-http-client#282] opened 2021-05-26 18:56 UTC
How could I solve `ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)` error? What may be the reason of this error?

```
>>> client = ipfshttpclient.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alper/venv/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py", line 119, in connect
    assert_version(client.apply_workarounds()["Version"])
  File "/home/alper/venv/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py", line 69, in assert_version
    raise exceptions.VersionMismatch(version, minimum, maximum)
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)
```

----------

```
$ pip freeze | grep ipfs
ipfshttpclient==0.7.0a1

$ pip freeze | grep daemon
daemon==1.2
python-daemon==2.3.0
```

Can we use `py-ipfs-http-client` along with `ipfs version v0.8.0`?

**Comment by ntninja** [comment] 2021-05-27 20:10
It does talk about the go-IPFS daemon version, yes. :slightly_smiling_face: 

For now just install the preview version and hope we get to release a proper version soon: `pip install ipfshttpclient==0.8.0a1` !

**Comment by avatar-lavventura** [comment] 2021-05-27 23:43
Thanks. Is it also recommended to install the master repo using `pip install git+https://github.com/ipfs-shipyard/py-ipfs-http-client` or should I stick with `0.8.0a1`?

**Comment by avatar-lavventura** [comment] 2021-07-17 12:38
> It does talk about the go-IPFS daemon version, yes. 🙂
> 
> For now just install the preview version and hope we get to release a proper version soon: `pip install ipfshttpclient==0.8.0a1` !

This issue is open since May. It will be helpful with a simple guidence.

Still `master-repo`, `v0.8.0a1`, `v0.8.0a2`gives: `~/venv/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py:75: VersionMismatch: Unsupported daemon version '0.9.0' (not in range: 0.5.0 ≤ … < 0.9.0)
  warnings.warn(exceptions.VersionMismatch(version, minimum, maximum))` warning message.

Will we able to use `py-ipfs-http-client` along with ipfs version 0.9.0? If yes, what is the proper way to do it?

**Comment by kasteph** [comment] 2023-05-16 18:06
This actually looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

Thanks.

**Closed by kasteph** 2023-05-16 18:06 UTC

**Comment by avatar-lavventura** [comment] 2023-05-16 19:57
@kasteph Since `May 26 2021`  there is no improvement in this issue. There has not been any focus in this over 2 years.

**Comment by kasteph** [comment] 2023-05-17 09:11
Hi @avatar-lavventura, thanks for your reply. I understand your concern and I have already started working on this issue [here](https://github.com/ipfs-shipyard/py-ipfs-http-client/pull/320).

The decision to keep #313 open was arbitrary. This doesn't mean that this isn't a valid issue, however. I simply think that they are talking about a similar issue and I'm trying to tidy up the issue tracker so that code contributors can focus instead of having to sift through duplicate issues.

**Comment by avatar-lavventura** [comment] 2023-05-17 12:44
@kasteph Thanks I appreciated your help!

**Comment by Admski** [comment] 2023-05-21 06:30
SOLUTION!: 
What worked for me on mac 13.2.1 was de-installing ipfs completly from the system. Deleting all files even on /usr/local/bin. After that installing ipfs version 0.7.0. This was working and looked like this:

Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
