### ISSUE TITLE
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.13.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by Wizock** [ipfs-shipyard/py-ipfs-http-client#315] opened 2022-06-22 11:00 UTC
Id really like to work with this library but unfortunately, its close to impossible to downgrade go-ipfs. Could someone tell me how to downgrade go-ipfs to what ever version is supported from march 2021 or how I can rectify this situation because I think the API is very simplistic

**Comment by moraisandreua** [comment] 2022-11-22 11:07
same problem for version 0.16. were you able to solve the issue?

**Comment by Amosharid** [comment] 2022-11-30 21:05
Hi both, Did any of you manage to use the library to interact with IPFS.
 I want to work with the library; however, I am stuck with the error that says unsupported daemon.
I am not able to downgrade the IPFS version.

**Comment by kasteph** [comment] 2023-05-16 18:04
This actually looks like a duplicate of #313 and it seems to be an ongoing problem whenever kubo upgrades. For any ongoing discussions/issues for this topic, I'd like to defer to the other issue so that it's easier to have the info in one place and focus.

Thanks.

**Closed by kasteph** 2023-05-16 18:04 UTC
