### ISSUE TITLE
client.id() is rejected when using go-ipfs beyond v0.4.23

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/py-ipfs-http-client#212] opened 2020-04-28 20:12 UTC
ipfshttpclient 0.4.13.2
Python 3.8
macOS 10.15.4

With go-ipfs v0.4.23
```py
>>> import ipfshttpclient
>>> x = ipfshttpclient.Client('/dns/localhost/tcp/5001/http')
>>> x.id()
ID': 'QmfYc...', 'PublicKey': 'CAASpg...
```

With go-ipfs 0.5.0-rc2 (supported per the README)
```py
>>> import ipfshttpclient
>>> x = ipfshttpclient.Client('/dns/localhost/tcp/5001/http')
>>> x.id()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 266, in _do_raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/base.py", line 15, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/miscellaneous.py", line 89, in id
    return self._client.request('/id', args, decoder='json', **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 51, in wrapper
    return func(self, *args, **merged)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 385, in request
    res = self._request(method, url, params, stream, files, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 307, in _request
    self._do_raise_for_status(res)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 286, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true
```

With go-ipfs 0.5.0 (current latest)
```py
>>> import ipfshttpclient
>>> x = ipfshttpclient.Client('/dns/localhost/tcp/5001/http')
>>> x.id()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 266, in _do_raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/base.py", line 15, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/miscellaneous.py", line 89, in id
    return self._client.request('/id', args, decoder='json', **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 51, in wrapper
    return func(self, *args, **merged)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 385, in request
    res = self._request(method, url, params, stream, files, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 307, in _request
    self._do_raise_for_status(res)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 286, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true
```

The daemons in the the last working version and the current seem to have similar output for the API on launch:

go-ipfs v0.5.0 daemon launch:
```
Swarm listening on /ip4/192.168.1.155/tcp/4001
Swarm listening on /ip4/192.168.1.167/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.155/tcp/4001
Swarm announcing /ip4/192.168.1.167/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

go-ipfs v0.4.23 daemon launch:
```
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.155/tcp/4001
Swarm listening on /ip4/192.168.1.167/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/100.34.119.17/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.155/tcp/4001
Swarm announcing /ip4/192.168.1.167/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

Hoping to figure this out for https://github.com/oduwsdl/ipwb/issues/638.

**Comment by ibnesayeed** [comment] 2020-04-28 21:01
I think this will be fixed when #204 is released. I guess the issues is caused by https://github.com/ipfs/go-ipfs/pull/7097.

**Closed** 2020-07-01 11:48 UTC
